/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRhRouteImport } from './routes/_app.rh'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppProducaoRouteImport } from './routes/_app.producao'
import { Route as AppPedidosRouteImport } from './routes/_app.pedidos'
import { Route as AppOrcamentosRouteImport } from './routes/_app.orcamentos'
import { Route as AppInstalacoesRouteImport } from './routes/_app.instalacoes'
import { Route as AppFornecedoresRouteImport } from './routes/_app.fornecedores'
import { Route as AppFiscalRouteImport } from './routes/_app.fiscal'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfigRouteImport } from './routes/_app.config'
import { Route as AppComprasRouteImport } from './routes/_app.compras'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRhRoute = AppRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppProducaoRoute = AppProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentosRoute = AppOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppInstalacoesRoute = AppInstalacoesRouteImport.update({
  id: '/instalacoes',
  path: '/instalacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFornecedoresRoute = AppFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => AppRoute,
} as any)
const AppFiscalRoute = AppFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/compras': typeof AppComprasRoute
  '/config': typeof AppConfigRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fiscal': typeof AppFiscalRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/instalacoes': typeof AppInstalacoesRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pedidos': typeof AppPedidosRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rh': typeof AppRhRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/clientes': typeof AppClientesRoute
  '/compras': typeof AppComprasRoute
  '/config': typeof AppConfigRoute
  '/dashboard': typeof AppDashboardRoute
  '/estoque': typeof AppEstoqueRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/fiscal': typeof AppFiscalRoute
  '/fornecedores': typeof AppFornecedoresRoute
  '/instalacoes': typeof AppInstalacoesRoute
  '/orcamentos': typeof AppOrcamentosRoute
  '/pedidos': typeof AppPedidosRoute
  '/producao': typeof AppProducaoRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/rh': typeof AppRhRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/compras': typeof AppComprasRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/fiscal': typeof AppFiscalRoute
  '/_app/fornecedores': typeof AppFornecedoresRoute
  '/_app/instalacoes': typeof AppInstalacoesRoute
  '/_app/orcamentos': typeof AppOrcamentosRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/producao': typeof AppProducaoRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/rh': typeof AppRhRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clientes'
    | '/compras'
    | '/config'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/fornecedores'
    | '/instalacoes'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/rh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/clientes'
    | '/compras'
    | '/config'
    | '/dashboard'
    | '/estoque'
    | '/financeiro'
    | '/fiscal'
    | '/fornecedores'
    | '/instalacoes'
    | '/orcamentos'
    | '/pedidos'
    | '/producao'
    | '/produtos'
    | '/relatorios'
    | '/rh'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/clientes'
    | '/_app/compras'
    | '/_app/config'
    | '/_app/dashboard'
    | '/_app/estoque'
    | '/_app/financeiro'
    | '/_app/fiscal'
    | '/_app/fornecedores'
    | '/_app/instalacoes'
    | '/_app/orcamentos'
    | '/_app/pedidos'
    | '/_app/producao'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/_app/rh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/rh': {
      id: '/_app/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AppRhRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/producao': {
      id: '/_app/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AppProducaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamentos': {
      id: '/_app/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof AppOrcamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instalacoes': {
      id: '/_app/instalacoes'
      path: '/instalacoes'
      fullPath: '/instalacoes'
      preLoaderRoute: typeof AppInstalacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fornecedores': {
      id: '/_app/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AppFornecedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fiscal': {
      id: '/_app/fiscal'
      path: '/fiscal'
      fullPath: '/fiscal'
      preLoaderRoute: typeof AppFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compras': {
      id: '/_app/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfigRoute: typeof AppConfigRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFiscalRoute: typeof AppFiscalRoute
  AppFornecedoresRoute: typeof AppFornecedoresRoute
  AppInstalacoesRoute: typeof AppInstalacoesRoute
  AppOrcamentosRoute: typeof AppOrcamentosRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppProducaoRoute: typeof AppProducaoRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppRhRoute: typeof AppRhRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfigRoute: AppConfigRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFiscalRoute: AppFiscalRoute,
  AppFornecedoresRoute: AppFornecedoresRoute,
  AppInstalacoesRoute: AppInstalacoesRoute,
  AppOrcamentosRoute: AppOrcamentosRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppProducaoRoute: AppProducaoRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppRhRoute: AppRhRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
